version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: 'laravel_noexpapi'
        container_name: NoExpApi
        ports:
            - "3700:8000"
        command: php artisan queue:work
networks: 
  default: 
    external: 
      name: raspisql_default 